name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Add fmt
      run: rustup component add rustfmt
    - name: Add Clippy
      run: rustup component add clippy
    - name: Format
      run: cargo fmt --all -- --check
    - name: Clippy
      run: cargo clippy
    - name: Run tests
      run: cargo test --verbose
